#! /bin/bash
set -e
set -u
set -o pipefail

# Sets up Atom for me

#cp config.cson ~/.atom;
#cp styles.less ~/.atom

filename="atomPackages.txt"

while read -r package
do
    apm install $package
    echo $package installed

done < "$filename"
