# ~/.bash_aliases: executed to load aliases from .bashrc

# per i download di youtube
alias youtube-dl='youtube-dl -f 18'

## Show hidden files only##
alias l.='ls -d .* --color=auto'

# handy short cuts #
alias ht="history | tail"
alias hd="history -d"
alias jobs='jobs -l'

#prompt if deleting more than 3 files at a time #
alias rm='rm -I'

# confirmation #
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'

## pass options to free ##
alias meminfo='free -m -l -t'

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'

## get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

## Get server cpu info ##
alias cpuinfo='lscpu'

## older system use /proc/cpuinfo ##
##alias cpuinfo='less /proc/cpuinfo' ##

## get GPU ram on desktop / laptop##
alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'

## this one saved by butt so many times ##
alias wget='wget -c'

## set some other defaults ##
alias df='df -h'
alias du='du -ch'

# BFG Repo Cleaner (https://rtyley.github.io/bfg-repo-cleaner/)
alias bfg="java -jar $HOME/Softwares/BFG/bfg.jar"

# http://superuser.com/questions/82408/sqlite-with-readline-support-on-ubuntu
# SQLite3 in debian is compiled without readline support "ldd $(which sqlite3)"
# You should recompile sqlite or use:
alias sqlite3="rlwrap sqlite3"

# using clipper in terminals
alias xclip="xclip -selection c"
