# ~/.bash_aliases: executed to load aliases from .bashrc

# per i download di youtube
alias youtube-dl='youtube-dl -f 18'

## Show hidden files only##
alias l.='ls -d .* --color=auto'

# handy short cuts #
alias ht="history | tail"
alias hd="history -d"
alias jobs='jobs -l'

#prompt if deleting more than 3 files at a time #
#alias rm='rm -I'
#alias rm="$HOME/bin/safe_rm"
alias rm='$HOME/bin/safe-rm -I'

# confirmation #
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'

## pass options to free ##
alias meminfo='free -m -l -t'

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'

## get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

## Get server cpu info ##
alias cpuinfo='lscpu'

## older system use /proc/cpuinfo ##
##alias cpuinfo='less /proc/cpuinfo' ##

## get GPU ram on desktop / laptop##
alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'

## this one saved by butt so many times ##
alias wget='wget -c'

## set some other defaults ##
alias df='df -h'
alias du='du -ch'

## Useful alias for docker: http://nathanleclaire.com/blog/2014/07/12/10-docker-tips-and-tricks-that-will-make-you-sing-a-whale-song-of-joy/
alias drm="docker rm"
alias dps="docker ps"
alias dpsa="docker ps -a"
alias dpse="docker ps -a | awk 'BEGIN { FS = \"[ ][ ]+\" } {if (\$5 ~ /^Exited/) {print \$0}}'"
alias dpseid="dpse | cut -f1 --delim=\" \""

# una function per attivare un docker e attaccarsi
function da () {
    docker start $1 && docker attach $1
}

# Dump della network di docker
function dgetnetwork() {
    docker inspect -f '{{ json .NetworkSettings }}' $1 | python -mjson.tool
}

# dump dell'ip address del container docker
function dgetipaddress() {
    docker inspect --format="{{.NetworkSettings.IPAddress}}" $1
}

# getta i volumi (updated 1.8.1)
# http://stackoverflow.com/questions/30133664/how-do-you-list-volumes-in-docker-containers
function dgetvolumes() {
    ddocker inspect -f '{{ (index .Mounts 0).Source }}' $1
}

# ripulisce i container stopped e le immagini non utilizzate
# http://stackoverflow.com/questions/32723111/how-to-remove-old-and-unused-docker-images
dcleanup(){
    docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
    docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null
}

# BFG Repo Cleaner (https://rtyley.github.io/bfg-repo-cleaner/)
alias bfg="java -jar $HOME/Softwares/BFG/bfg.jar"

# http://superuser.com/questions/82408/sqlite-with-readline-support-on-ubuntu
# SQLite3 in debian is compiled without readline support "ldd $(which sqlite3)"
# You should recompile sqlite or use:
alias sqlite3="rlwrap sqlite3"
