# ~/.bash_aliases: executed to load aliases from .bashrc

# per i download di youtube
alias youtube-dl='youtube-dl -f 18'

## Show hidden files only##
alias l.='ls -d .* --color=auto'

# handy short cuts #
alias ht="history | tail"
alias hd="history -d"
alias jobs='jobs -l'

#prompt if deleting more than 3 files at a time #
alias rm='rm -I'

# confirmation #
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'

## pass options to free ##
alias meminfo='free -m -l -t'

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'

## get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

## Get server cpu info ##
alias cpuinfo='lscpu'

## older system use /proc/cpuinfo ##
##alias cpuinfo='less /proc/cpuinfo' ##

## get GPU ram on desktop / laptop##
alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'

## this one saved by butt so many times ##
alias wget='wget -c'

## set some other defaults ##
alias df='df -h'
alias du='du -ch'

## Useful alias for docker: http://nathanleclaire.com/blog/2014/07/12/10-docker-tips-and-tricks-that-will-make-you-sing-a-whale-song-of-joy/
alias drm="docker rm"
alias dps="docker ps"
alias dpsa="docker ps -a"
alias dpse="docker ps -a | awk 'BEGIN { FS = \"[ ][ ]+\" } {if (\$5 ~ /^Exited/) {print \$0}}'"
alias dpseid="dpse | cut -f1 --delim=\" \""

# una function per attivare un docker e attaccarsi
function da () {
    docker start $1 && docker attach $1
}

function dgetnetwork() {
    docker inspect -f '{{ json .NetworkSettings }}' $1 | python -mjson.tool
}

function dgetvolumes() {
    docker inspect -f '{{ index .Volumes "/host/path" }}' $1
}
