#!/bin/sh

# for more info, visit:
# https://medium.com/@cjus/handy-docker-aliases-4bd85089a3b8

alias dm='docker-machine'
alias dmx='docker-machine ssh'
alias dk='docker'
alias dki='docker images'
alias dks='docker service'
alias dkrm='docker rm'
alias dkrmi='docker rmi'
alias dkl='docker logs'
alias dklf='docker logs -f'
alias dkflush='docker rm `docker ps --no-trunc -aq`'
alias dkflush2='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'
alias dkt='docker stats --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}"'
alias dkps="docker ps --format '{{.ID}} ~ {{.Names}} ~ {{.Status}} ~ {{.Image}}'"

## Useful alias for docker:
# http://nathanleclaire.com/blog/2014/07/12/10-docker-tips-and-tricks-that-will-make-you-sing-a-whale-song-of-joy/
# adapted in order to have always dk for docker commands
alias dkpsa="docker ps -a"
alias dkpse="docker ps -a | awk 'BEGIN { FS = \"[ ][ ]+\" } {if (\$5 ~ /^Exited/) {print \$0}}'"
alias dkpseid="dpse | cut -f1 --delim=\" \""

# when docker compose plugin is installed
alias docker-compose="docker compose"

# activate a container then attach to it
function dka () {
    docker start $1 && docker attach $1
}

# dumping the network settings of a container
function dkgetnetwork() {
    docker inspect -f '{{ json .NetworkSettings }}' $1 | jq
}

# dumping the ip address of a container
function dkgetipaddress() {
    docker inspect --format="{{.NetworkSettings.IPAddress}}" $1
}

# collect the volumes of a container
# http://stackoverflow.com/questions/30133664/how-do-you-list-volumes-in-docker-containers
function dkgetvolumes() {
    ddocker inspect -f '{{ (index .Mounts 0).Source }}' $1
}

# to collect labels
function dkgetlabels() {
    docker inspect --format '{{json .Config.Labels}}' $1 | jq
}

# clean up stopped containers and dangling images
# http://stackoverflow.com/questions/32723111/how-to-remove-old-and-unused-docker-images
dkcleanup(){
    docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
    docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null
}

# dkln: Follows the logs of a running Docker container whose name matches the given pattern.
# Usage: dkln <container_name_pattern>
# Example: dkln myapp
# This will attach to the logs of the first container whose name contains "myapp".
dkln() {
  docker logs -f `docker ps | grep $1 | awk '{print $1}'`
}

dkclean() {
  docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
  docker volume rm $(docker volume ls -qf dangling=true 2>/dev/null) 2>/dev/null
  docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null
}

dkprune() {
  docker system prune -af
}

dktop() {
  docker stats --format "table {{.Container}}\t{{.Name}}\t{{.CPUPerc}}  {{.MemPerc}}\t{{.NetIO}}\t{{.BlockIO}}"
}

dkstats() {
  if [ $# -eq 0 ]
    then docker stats --no-stream;
    else docker stats --no-stream | grep $1;
  fi
}

dke() {
  docker exec -it $1 /bin/sh
}

dkexe() {
  docker exec -it $1 $2
}

dkstate() {
  docker inspect $1 | jq .[0].State
}

dksb() {
  docker service scale $1=0
  sleep 2
  docker service scale $1=$2
}

# https://forums.docker.com/t/how-can-i-list-tags-for-a-repository/32577/7
function listTags() {
  local repo=${1}
  local size=${2:-25}
  local page=${3:-1}
  [ -z "${repo}" ] && echo "Usage: listTags <repoName> [size] [pageIndex]" 1>&2 && return 1
  curl "https://registry.hub.docker.com/api/content/v1/repositories/public/library/${repo}/tags?page=${page}&page_size=${size}" 2>/dev/null | jq -r '.results[].name' | sort
}

function dksearchtags() {
  local repo=${1}
  local count=$(curl "https://registry.hub.docker.com/api/content/v1/repositories/public/library/${repo}/tags" 2>/dev/null | jq -r '.count')
  local size=25
  let totPages=${count}/${size}
  let reminder=${count}%${size}
  if (( reminder > 0 )); then
    ((totPages+=1))
  fi
  #echo ${count} ${size} ${totPages} ${reminder}
  for page in $(seq 1 ${totPages}); do
    listTags ${repo} ${size} ${page}
  done
}
